### PR TITLE
Add option to link with MSVC static runtime (OFF by default)

### PR DESCRIPTION
**Pull request by sgallou**
Like for [oatpp](https://github.com/oatpp/oatpp/pull/435), [oatpp-swagger](https://github.com/oatpp/oatpp-swagger/pull/51) and [oatpp-websocket](https://github.com/oatpp/oatpp-websocket/pull/29), add option to link with MSVC static runtime (OFF by default)

### CODE REVIEW

**Comment by sgallou** [comment]
I don't understand why some checks failed (not all). OpenSSL seem's to be missing. @lganzzzo , can you check why, please ?

**Comment by sgallou** [comment]
Seems that MacOS build failed because of OpenSSL dependency not found by CMake. I think that problem is related to the build job, not to my changes.

Detailed error message is "Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY OPENSSL_INCLUDE_DIR) (Required is at least version "1.1")

@lganzzzo Can you check that ?

**Comment by lganzzzo** [comment]
@sgallou ,
Yes, it looks like the issue of vcpkg which is used in Mac pipeline.
If it continue to occur - I'll remove vcpkg from the Mac pipeline.
Rerunning...

**Comment by sgallou** [comment]
@lganzzzo Same problem again :-(

**Comment by lganzzzo** [comment]
Merged.
Thanks for the PR!
I'll update the pipeline...

**Pull request merged**
